#!/command/with-contenv sh
set -e
exec s6-setuidgid devpi \
  /opt/devpi/bin/devpi-server \
    --serverdir /state/cache-package/pip \
    --host 0.0.0.0 \
    --port 3141 \
    --restrict-modify=root \
    --mirror-cache-expiry=1800
